org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.java.installations.auto-detect=true
org.gradle.java.installations.auto-download=true
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.235
loader_version_range=[1,)
mod_id=zhonz_more_enchantments
mod_name=Zhonz's More Enchantments
mod_license=All Rights Reserved
mod_version=1.3.2
mod_group_id=com.zhonz.moreenchantments
apothic_attributes_version=1.21.1-2.10.1
placebo_version=1.21.1-9.9.2
